# Generated by Django 5.0.6 on 2024-06-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
